[package]
name = "aoc2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
derive_more = "^0.99.17"
ndarray = "^0.15.4"
bitvec="^0.22.3"
rayon="^1.5.1"
rand="^0.8.4"